const SET_USER_DETAILS = 'SET_USER_DETAILS';
const SET_REGISTERED_USER = 'SET_REGISTERED_USER';
const SET_VALIDATE_MESSAGE = 'SET_VALIDATE_MESSAGE';
const RESET_VALIDATE_MESSAGE = 'RESET_VALIDATE_MESSAGE';

export {
  SET_USER_DETAILS,
  SET_REGISTERED_USER,
  SET_VALIDATE_MESSAGE,
  RESET_VALIDATE_MESSAGE
};